name: Cypress Tests

on: 
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-restore.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore caches
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            ~/.cache/Cypress
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Save caches
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            ~/.npm
            ~/.cache/Cypress
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

  cypress-electron-tests:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            ~/.cache/Cypress
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests (Electron)
        run: node runner.js electron
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}

  cypress-chrome-tests:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            ~/.cache/Cypress
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests (Chrome)
        run: node runner.js chrome
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
