name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run
          
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:firefox107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: Run E2E test
        uses: cypress-io/github-action@v6
        with:
          browser: firefox

  cypress-chrome-tests:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4
        
      - name: install dependencies
        run: npm install
        
      - name: Run E2E test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
       

        
