name: Optimized Cypress Tests

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Upload node_modules Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

  cypress-electron-tests:
    name: Run Cypress Tests in Electron
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Run Electron Tests
        run: node runner.js electron
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}

  cypress-chrome-tests:
    name: Run Cypress Tests in Chrome
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Run Chrome Tests
        run: node runner.js chrome
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
