name: Cypress Tests

on: 
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Electron
        run: node runner.js electron
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}

  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Chrome
        run: node runner.js chrome
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
